### ISSUE TITLE
Port installs 1 GiB of fonts

### ISSUE THREAD

**Issue by forkbomb9** [the-homura-project/homura-port#1]
The Makefile requires x11-fonts/noto, which is a metaport of noto-basic noto-extra noto noto-kr noto-sc noto-tc.
For people who do not have Korean/Chinese/Japanese fonts on their systems, it doesn't make sense to install all those fonts, so Homura should have only noto-basic as dependency.

**Comment by Alexander88207** [comment]
Hello @forkbomb9, i know but its requiered for teamspeak 3 and to kill other fonts issues with JP and Chinese games etc.. i took the meta package.

**Comment by forkbomb9** [comment]
So maybe it could be put as an optional dependency? And note it on the post-install note? Because I have to force uninstall them as it breaks the font display on Sway
 BTW, does FreeBSD support optional dependencies?:thinking:

**Comment by Alexander88207** [comment]
You can just edit the Makefile and remove [Line 26](https://github.com/the-homura-project/homura-port/blob/master/Makefile#L26) and also remove the `\` after `mesa-demos`. Then x11/noto should not be pulled as dep again :)

**Comment by forkbomb9** [comment]
Yeah, that will work. But you know, I think this should be optional, as everybody will play games with Homura, but not everyone will play Chinese games/use TeamSpeak... And it's easier to run `pkg install games/homura x11-fonts/noto` than having to clone the repo/fetch the ports, edit the file and run make, also you have to install the deps beforehand or build them from source...

**Comment by Alexander88207** [comment]
>  as everybody will play games with Homura, but not everyone will play Chinese games/use TeamSpeak

You may be right, but before i get reports why this or that doesn't work, i better ship everything what is needed.

---------------------------------------------------------------------------------------------------------------------------------------
In FreeBSD you have to take care of this yourself if you dont like things like this. For example, not everyone wants a port with/without pulseaudio, so you have to build it yourself with/without pulseaudio.

If you should have temporary memory (or other) problems because of this then i am sorry.

**Comment by Alexander88207** [comment]
I think that would have taken care of the topic. Have fun playing. :joystick:

**Comment by Alexander88207** [comment]
x11-fonts/noto will be now a optional depdendcy because it breaks uplay installation but fixes teamspeak 3 installation :smile:
